### ISSUE TITLE
where is data_recorder/tests/test_extract_features.py?

### ISSUE THREAD

**Issue by fodrh1201** [sadighian/crypto-rl#13]
is not yet implemented test_extract_features.py?
I cannot find the file.

**Comment by sadighian** [comment]
test_extract_features is a method implemented in [test_simulator.py](https://github.com/RedBanies3ofThem/crypto-rl/blob/arctic-streaming-ticks-full/data_recorder/tests/test_simulator.py).

See lines 51-72 for test_extract_features().

**Comment by sadighian** [comment]
[README](https://github.com/RedBanies3ofThem/crypto-rl/blob/arctic-streaming-ticks-full/README.md) has been updated to reflect the correct filename.

**Comment by fodrh1201** [comment]
thanks!
