### ISSUE TITLE
import error when running simulator

### ISSUE THREAD

**Issue by robertalanm** [sadighian/crypto-rl#15]
Hello, I keep running into this error stating that:
![image](https://user-images.githubusercontent.com/17856706/70753618-cb834180-1cfa-11ea-8539-f344e2aa3e58.png)

How do I fix?

**Comment by sadighian** [comment]
In general, the Python `ModuleNotFoundError` is thrown if a module is being reference that has not yet been installed. Can you confirm if you've installed `crypto-rl`? _Note: you should use a virtual environment when installing dependencies._ 

You can do the following steps to install the `crypto-rl` project in a virtual environment:

1. Create a virtual Environment in the root of the project:
`python3 -m venv ./venv`

2. Activate the virtual environment:
`source venv/bin/activate`

3. Install the crypto-rl project:
`pip3 install -e .`
