### ISSUE TITLE
it should be have a2c.py ppo.py?

### ISSUE THREAD

**Issue by playmyswift** [sadighian/crypto-rl#17]
thanks for you repo, I read your paper, the repo dose't have ppo.py? because `.gitignore` file include,
```
agent/dqn_weights/*
agent/ppo_weights/*
agent/acer_weights/*
agent/a2c_weights/*
```
https://github.com/sadighian/crypto-rl/commit/5cfbdf1d175fe7554e337337866bec82f73eca9b
so, I want to replay your paper test, but I don't know how can create `ppo` `acer` `a2c`.py

**Comment by playmyswift** [comment]
and it seems dqn looks like the worst?

**Comment by sadighian** [comment]
Hi @ericjjj ,

This repo is not the source code to the papers, but a platform for people to accelerate their RL research (i.e., data collection and integration is already provided).  

The DQN agent provided in this repo serves as a "hello world" example for platform integration with an RL algorithm.  If you are interested in extending the platform to use other RL algos (i.e., PPO, ACER, A2C, ...), then it might be helpful to look at the source code in `dqn.py`.
