### ISSUE TITLE
LOB training from historial LOB

### ISSUE THREAD

**Issue by elnazsn1988** [sadighian/crypto-rl#18]
Hi - Thanks for the awesome repo, am trying to understand how I can use your algorithm to train a DQN agent on historical LOB data on agent has seen for one asset (time, Bid Price, Ask Price, Bid Quantity, Ask Quantity, Order side) with Quantity being 0 when no order has been fulfilled but prices have fluctuated. When reviewing the data under recording : demo_LTC-USD_20190926.csv.xz , there are multiple columns specific to cryptocurrencies I assume, whereas I only have basic info. Is there a way/example to use historical LOB for any HFT other than crypto, or is the algorithm bespoke to the additional columns existent for cryptocurrencies?

**Comment by sadighian** [comment]
Hello @elnazsn1988 , 

It is possible to use _any_ data source with the `gym_trading` framework in this repo--although, it is already connected and ready-to-go with crypto data, which is free to obtain.

All that is needed to integrate with other data sources is the correct mapping of data values to columns (assuming you're using a CSV for training). The `demo_LTC-USD_20190926.csv.xz` file contains column headers, so you can use that file as an example of the columns (i.e., data model). Alternatively, you can look at the [source code](https://github.com/sadighian/crypto-rl/blob/arctic-streaming-ticks-full/data_recorder/connector_components/book.py).
