### ISSUE TITLE
Python version required

### ISSUE THREAD

**Issue by munirjojoverge** [sadighian/crypto-rl#24]
I've been trying to install on 3.7, 3.8 and 3.9.. It looks like always there is at least a few dependencies that fail to satisfy all your requirements. What python version did you use?
BTW I'm using Ubuntu 20.04

**Comment by snussik** [comment]
>  What python version did you use?

@munirjojoverge  Use 3.6.x, bro. As at least, arctic and tensonflow 1.x work with it.

**Comment by sadighian** [comment]
Hi @munirjojoverge,

When I started this project years ago, I used Ubuntu 18+ with Python 3.6. That said, I can confirm that this project (i.e., Data pipeline, POMDP framework) works with Ubuntu 20+ with Python 3.8.
